return {
    basePaths = {
        {"__DIRECTORY", "Guns", "Standard", "Sniper"},
        {"__DIRECTORY", "Guns", "Standard", "Minigun"},
        {"__DIRECTORY", "Guns", "Standard", "Rifle"},
    },
    
    variants = {
        Sniper = {
            base = "",
            yellow = "Variants/Yellow Glowstick Sniper",
            karat = "Variants/24 Karat Sniper",
            carnage = "Variants/Carnage Sniper",
            cherry = "Variants/Cherry Wood Sniper",
            leopard = "Variants/Clouded Leopard Sniper",
            cyan = "Variants/Cyan Glowstick Sniper",
            elite = "Variants/Elite Sniper",
            circus = "Variants/Evil Circus Sniper",
            futura = "Variants/Futura Sniper",
            ghostfire = "Variants/Ghostfire Sniper",
            graffiti = "Variants/Graffiti Sniper",
            indigo = "Variants/Indigo Camo Sniper",
            joystick = "Variants/Joystick Sniper",
            lovebomb = "Variants/Lovebomb Sniper",
            merry = "Variants/Merry Sniper",
            money = "Variants/Money Sniper",
            mosaic = "Variants/Mosaic Sniper",
            mummy = "Variants/Mummywrap Sniper",
            red = "Variants/Red Glowstick Sniper",
            ryu = "Variants/Ryu Sniper",
            scarlet = "Variants/Scarlet Sniper",
            spitfire = "Variants/Spitfire Sniper",
            starfall = "Variants/Starfall Sniper",
            sunbaked = "Variants/Sunbaked Sniper",
            sundown = "Variants/Sundown Sniper",
            unit = "Variants/UNIT007 Sniper",
            vampire = "Variants/Vampire Slayer Sniper",
            verglas = "Variants/Verglas Sniper",
            virus = "Variants/Virus Sniper",
            volcanic = "Variants/Volcanic Sniper",
            whiteout = "Variants/Whiteout Sniper"
        },
        Minigun = {
            base = "",
            karat = "Variants/24 Karat Minigun",
            carnage = "Variants/Carnage Minigun",
            cherry = "Variants/Cherry Wood Minigun",
            comic = "Variants/Comic Minigun",
            elite = "Variants/Elite Minigun",
            futura = "Variants/Futura Minigun",
            ghostfire = "Variants/Ghostfire Minigun",
            graffiti = "Variants/Graffiti Minigun",
            guerrilla = "Variants/Guerrilla Minigun",
            lovebomb = "Variants/Lovebomb Minigun",
            merry = "Variants/Merry Minigun",
            money = "Variants/Money Minigun",
            neonrider = "Variants/Neon Rider Minigun",
            overdrive = "Variants/Overdrive Minigun",
            purple = "Variants/Purple Camo Minigun",
            ryu = "Variants/Ryu Minigun",
            spitfire = "Variants/Spitfire Minigun",
            starfall = "Variants/Starfall Minigun",
            stitched = "Variants/Stitched Minigun",
            sundown = "Variants/Sundown Minigun",
            tiger = "Variants/Tiger Print Minigun",
            unit = "Variants/UNIT006 Minigun",
            whiteout = "Variants/Whiteout Minigun",
            zebra = "Variants/Zebra Minigun"
        },
        Rifle = {
            base = "",
            karat = "Variants/24 Karat Rifle",
            arctic = "Variants/Arctic Camo Rifle",
            camo = "Variants/Camo Rifle",
            carbon = "Variants/Carbon Fiber Rifle",
            comic = "Variants/Comic Rifle",
            corroded = "Variants/Corroded Rifle",
            elite = "Variants/Elite Rifle",
            futura = "Variants/Futura Rifle",
            ghostfire = "Variants/Ghostfire Rifle",
            graffiti = "Variants/Graffiti Rifle",
            green = "Variants/Green Glowstick Rifle",
            guerrilla = "Variants/Guerrilla Rifle",
            joystick = "Variants/Joystick Rifle",
            lovebomb = "Variants/Lovebomb Rifle",
            merry = "Variants/Merry Rifle",
            money = "Variants/Money Rifle",
            neonrider = "Variants/Neon Rider Rifle",
            overdrive = "Variants/Overdrive Rifle",
            petrified = "Variants/Petrified Rifle",
            retro = "Variants/Retro Rifle",
            ryu = "Variants/Ryu Rifle",
            spitfire = "Variants/Spitfire Rifle",
            starfall = "Variants/Starfall Rifle",
            sunbaked = "Variants/Sunbaked Rifle",
            sundown = "Variants/Sundown Rifle",
            tiger = "Variants/Tiger Print Rifle",
            unit = "Variants/UNIT005 Rifle",
            violet = "Variants/Violet Glowstick Rifle",
            volcanic = "Variants/Volcanic Rifle",
            voodoo = "Variants/Voodoo Rifle",
            whiteout = "Variants/Whiteout Rifle",
            zebra = "Variants/Zebra Rifle",
            zombie = "Variants/Zombie Rifle"
        },
    }
} 